{% set version = "1.10.1" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 3fa11d143ba9a60802686af23942848067181771c7558a369b3e1476ad54ba9f

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python
    - pip
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
