{% set version = "1.10.0a2" %}

package:
  name: holoviews
  version: {{ version }}

source:
  git_url: https://github.com/ioam/holoviews.git
  git_rev: v{{version}}
  git_depth: 1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - numpy
    - param
    - setuptools
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
