travis:
  secure:
    BINSTAR_TOKEN: h0RlkUynJtuzf0zxvkMHn5/Yt++S4R9pr09VXQiLMFIFN+xYsoz6DLxGhfI5PoQLzuxzX7N3LVffo/oPuufnQHlFYX6fLcspsSVFZ/tBqrS01Fbt4EIErw18NkU3SWqt7ZArLDpSbgM11z69zmlx1AvsibhLjNM51tdahsUt4SMF5Di0ZcZ0Rsn8FWbC/ydSMYc8IkYtSNtS+5mMKbCOpji0P+ROKqHE5KvPucnM6PAtJMehx4Ovbb4kFjLTWSEUwSifCJizsxZfM1iEvEVZCKrQr2cd8IXpTTZRmTPXdfBataoh4x81wnCEz0iE6hpV7MtR4amSWrXABBHsPh10HCqntWhsLfUukAnHlvrsDXx2IezzZp64jlCsvaRsU/B3ZfPTqCRIRD8lU7F9TncQo14M6Hhk7Yj2HJfyIjH4QzOc5b1ZDvpt3UCZc3VnC6agi6tku78Td/STzeLlwNBqpoXb8OvdmxWuBwOfXRHI+mk8yDkJ4mRK0N52WzFLeI/aN0e5+hJ3nsv4wPy/nRfdjwsBZNibanAXqAJgG5U1NlbTvZuBTfPU2ufnG10m7jUIqG/NS7cEaj5zKjqmzOMO6xLFhlDmKylOXQoz72s5cLAhCnfb0tlYafupp+z61h3x25lOqBcMsxq2hfNgouhrqAQvu7O9bIifmyBV/NinZWM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
